### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 12345
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e598430196eb43d3be0d966279eb2160",
  "accountNumber": "1000000000",
  "amount": 12345
}

### query transaction
GET http://localhost:8080/transaction/13eb9149aff447f6b4d6bd3be83f6e8a
